In [1]:
import pandas as pd

df = pd.read_csv("monthly_neighbourhood_safety_from_cleaned.csv")
df.head()

,occ_month,neighbourhood_158,longitude_wgs84,latitude_wgs84,assault_count,robbery_count,break_and_enter_count,auto_theft_count,theft_over_count,incident_count,total_crime_score,global_min_score,global_max_score,safety_index
0,Jan-14,Agincourt North (129),-79.270573,43.808031,7,5,3,2,1,18,69,1,528,0.870968
1,Jan-14,Agincourt South-Malvern West (128),-79.270418,43.787612,8,1,17,5,0,31,105,1,528,0.802657
2,Jan-14,Alderwood (20),-79.543571,43.605431,4,0,2,0,1,7,27,1,528,0.950664
3,Jan-14,Annex (95),-79.400752,43.670308,19,4,12,0,3,38,150,1,528,0.717268
4,Jan-14,Avondale (153),-79.406814,43.760235,0,0,2,1,1,4,9,1,528,0.984820

In [2]:
df.columns

Index(['occ_month', 'neighbourhood_158', 'longitude_wgs84', 'latitude_wgs84',
       'assault_count', 'robbery_count', 'break_and_enter_count',
       'auto_theft_count', 'theft_over_count', 'incident_count',
       'total_crime_score', 'global_min_score', 'global_max_score',
       'safety_index'],
      dtype='object')

In [6]:
pd.set_option("display.max_rows", None)
df.groupby("neighbourhood_158")[["longitude_wgs84", "latitude_wgs84"]].nunique()

                                             longitude_wgs84  latitude_wgs84
neighbourhood_158
Agincourt North (129)                                      1               1
Agincourt South-Malvern West (128)                         1               1
Alderwood (20)                                             1               1
Annex (95)                                                 1               1
Avondale (153)                                             1               1
Banbury-Don Mills (42)                                     1               1
Bathurst Manor (34)                                        1               1
Bay-Cloverhill (169)                                       1               1
Bayview Village (52)                                       1               1
Bayview Woods-Steeles (49)                                 1               1
Bedford Park-Nortown (39)                                  1               1
Beechborough-Greenbrook (112)                              1               1
Bendale South (157)                                        1               1
Bendale-Glen Andrew (156)                                  1               1
Birchcliffe-Cliffside (122)                                1               1
Black Creek (24)                                           1               1
Blake-Jones (69)                                           1               1
Briar Hill-Belgravia (108)                                 1               1
Bridle Path-Sunnybrook-York Mills (41)                     1               1
Broadview North (57)                                       1               1
Brookhaven-Amesbury (30)                                   1               1
Cabbagetown-South St.James Town (71)                       1               1
Caledonia-Fairbank (109)                                   1               1
Casa Loma (96)                                             1               1
Centennial Scarborough (133)                               1               1
Church-Wellesley (167)                                     1               1
Clairlea-Birchmount (120)                                  1               1
Clanton Park (33)                                          1               1
Cliffcrest (123)                                           1               1
Corso Italia-Davenport (92)                                1               1
Danforth (66)                                              1               1
Danforth East York (59)                                    1               1
Don Valley Village (47)                                    1               1
Dorset Park (126)                                          1               1
Dovercourt Village (172)                                   1               1
Downsview (155)                                            1               1
Downtown Yonge East (168)                                  1               1
Dufferin Grove (83)                                        1               1
East End-Danforth (62)                                     1               1
East L'Amoreaux (148)                                      1               1
East Willowdale (152)                                      1               1
Edenbridge-Humber Valley (9)                               1               1
Eglinton East (138)                                        1               1
Elms-Old Rexdale (5)                                       1               1
Englemount-Lawrence (32)                                   1               1
Eringate-Centennial-West Deane (11)                        1               1
Etobicoke City Centre (159)                                1               1
Etobicoke West Mall (13)                                   1               1
Fenside-Parkwoods (150)                                    1               1
Flemingdon Park (44)                                       1               1
Forest Hill North (102)                                    1               1
Forest Hill South (101)                                    1               1
Fort York-Liberty Village (163)                            1               1
Glenfield-Jane Heights (25)                                1               1
Golfdale-Cedarbrae-Woburn (141)                            1               1
Greenwood-Coxwell (65)                                     1               1
Guildwood (140)                                            1               1
Harbourfront-CityPlace (165)                               1               1
Henry Farm (53)                                            1               1
High Park North (88)                                       1               1
High Park-Swansea (87)                                     1               1
Highland Creek (134)                                       1               1
Hillcrest Village (48)                                     1               1
Humber Bay Shores (161)                                    1               1
Humber Heights-Westmount (8)                               1               1
Humber Summit (21)                                         1               1
Humbermede (22)                                            1               1
Humewood-Cedarvale (106)                                   1               1
Ionview (125)                                              1               1
Islington (158)                                            1               1
Junction Area (90)                                         1               1
Junction-Wallace Emerson (171)                             1               1
Keelesdale-Eglinton West (110)                             1               1
Kennedy Park (124)                                         1               1
Kensington-Chinatown (78)                                  1               1
Kingsview Village-The Westway (6)                          1               1
Kingsway South (15)                                        1               1
L'Amoreaux West (147)                                      1               1
Lambton Baby Point (114)                                   1               1
Lansing-Westgate (38)                                      1               1
Lawrence Park North (105)                                  1               1
Lawrence Park South (103)                                  1               1
Leaside-Bennington (56)                                    1               1
Little Portugal (84)                                       1               1
Long Branch (19)                                           1               1
Malvern East (146)                                         1               1
Malvern West (145)                                         1               1
Maple Leaf (29)                                            1               1
Markland Wood (12)                                         1               1
Milliken (130)                                             1               1
Mimico-Queensway (160)                                     1               1
Morningside (135)                                          1               1
Morningside Heights (144)                                  1               1
Moss Park (73)                                             1               1
Mount Dennis (115)                                         1               1
Mount Olive-Silverstone-Jamestown (2)                      1               1
Mount Pleasant East (99)                                   1               1
New Toronto (18)                                           1               1
Newtonbrook East (50)                                      1               1
Newtonbrook West (36)                                      1               1
North Riverdale (68)                                       1               1
North St.James Town (74)                                   1               1
North Toronto (173)                                        1               1
O'Connor-Parkview (54)                                     1               1
Oakdale-Beverley Heights (154)                             1               1
Oakridge (121)                                             1               1
Oakwood Village (107)                                      1               1
Old East York (58)                                         1               1
Palmerston-Little Italy (80)                               1               1
Parkwoods-O'Connor Hills (149)                             1               1
Pelmo Park-Humberlea (23)                                  1               1
Playter Estates-Danforth (67)                              1               1
Pleasant View (46)                                         1               1
Princess-Rosethorn (10)                                    1               1
Regent Park (72)                                           1               1
Rexdale-Kipling (4)                                        1               1
Rockcliffe-Smythe (111)                                    1               1
Roncesvalles (86)                                          1               1
Rosedale-Moore Park (98)                                   1               1
Runnymede-Bloor West Village (89)                          1               1
Rustic (28)                                                1               1
Scarborough Village (139)                                  1               1
South Eglinton-Davisville (174)                            1               1
South Parkdale (85)                                        1               1
South Riverdale (70)                                       1               1
St Lawrence-East Bayfront-The Islands (166)                1               1
St.Andrew-Windfields (40)                                  1               1
Steeles (116)                                              1               1
Stonegate-Queensway (16)                                   1               1
Tam O'Shanter-Sullivan (118)                               1               1
Taylor-Massey (61)                                         1               1
The Beaches (63)                                           1               1
Thistletown-Beaumond Heights (3)                           1               1
Thorncliffe Park (55)                                      1               1
Trinity-Bellwoods (81)                                     1               1
University (79)                                            1               1
Victoria Village (43)                                      1               1
Wellington Place (164)                                     1               1
West Hill (136)                                            1               1
West Humber-Clairville (1)                                 1               1
West Queen West (162)                                      1               1
West Rouge (143)                                           1               1
Westminster-Branson (35)                                   1               1
Weston (113)                                               1               1
Weston-Pelham Park (91)                                    1               1
Wexford/Maryvale (119)                                     1               1
Willowdale West (37)                                       1               1
Willowridge-Martingrove-Richview (7)                       1               1
Woburn North (142)                                         1               1
Woodbine Corridor (64)                                     1               1
Woodbine-Lumsden (60)                                      1               1
Wychwood (94)                                              1               1
Yonge-Bay Corridor (170)                                   1               1
Yonge-Doris (151)                                          1               1
Yonge-Eglinton (100)                                       1               1
Yonge-St.Clair (97)                                        1               1
York University Heights (27)                               1               1
Yorkdale-Glen Park (31)                                    1               1

In [3]:
print(df["occ_month"].unique())
print(df["occ_month"].dtype)

['Jan-14' 'Feb-14' 'Mar-14' 'Apr-14' 'May-14' 'Jun-14' 'Jul-14' 'Aug-14'
 'Sep-14' 'Oct-14' 'Nov-14' 'Dec-14' 'Jan-15' 'Feb-15' 'Mar-15' 'Apr-15'
 'May-15' 'Jun-15' 'Jul-15' 'Aug-15' 'Sep-15' 'Oct-15' 'Nov-15' 'Dec-15'
 'Jan-16' 'Feb-16' 'Mar-16' 'Apr-16' 'May-16' 'Jun-16' 'Jul-16' 'Aug-16'
 'Sep-16' 'Oct-16' 'Nov-16' 'Dec-16' 'Jan-17' 'Feb-17' 'Mar-17' 'Apr-17'
 'May-17' 'Jun-17' 'Jul-17' 'Aug-17' 'Sep-17' 'Oct-17' 'Nov-17' 'Dec-17'
 'Jan-18' 'Feb-18' 'Mar-18' 'Apr-18' 'May-18' 'Jun-18' 'Jul-18' 'Aug-18'
 'Sep-18' 'Oct-18' 'Nov-18' 'Dec-18' 'Jan-19' 'Feb-19' 'Mar-19' 'Apr-19'
 'May-19' 'Jun-19' 'Jul-19' 'Aug-19' 'Sep-19' 'Oct-19' 'Nov-19' 'Dec-19'
 'Jan-20' 'Feb-20' 'Mar-20' 'Apr-20' 'May-20' 'Jun-20' 'Jul-20' 'Aug-20'
 'Sep-20' 'Oct-20' 'Nov-20' 'Dec-20' 'Jan-21' 'Feb-21' 'Mar-21' 'Apr-21'
 'May-21' 'Jun-21' 'Jul-21' 'Aug-21' 'Sep-21' 'Oct-21' 'Nov-21' 'Dec-21'
 'Jan-22' 'Feb-22' 'Mar-22' 'Apr-22' 'May-22' 'Jun-22' 'Jul-22' 'Aug-22'
 'Sep-22' 'Oct-22' 'Nov-22' 'Dec-22' 'Jan-23' 'Feb-23' 'Mar-23' 'Apr-23'
 'May-23' 'Jun-23' 'Jul-23' 'Aug-23' 'Sep-23' 'Oct-23' 'Nov-23' 'Dec-23'
 'Jan-24' 'Feb-24' 'Mar-24' 'Apr-24' 'May-24' 'Jun-24' 'Jul-24' 'Aug-24'
 'Sep-24' 'Oct-24' 'Nov-24' 'Dec-24' 'Jan-25' 'Feb-25' 'Mar-25' 'Apr-25'
 'May-25' 'Jun-25' 'Jul-25' 'Aug-25' 'Sep-25' 'Oct-25' 'Nov-25' 'Dec-25']
object

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("data/monthly_neighbourhood_safety_from_cleaned.csv")

plt.figure(figsize=(8, 5))
plt.boxplot(df["safety_index"].dropna(), vert=True, patch_artist=True)
plt.ylabel("Safety Index")
plt.title("Box Plot of Safety Index")
plt.grid(axis="y", linestyle="--", alpha=0.4)
plt.show()